import { describe, expect, test } from "bun:test"
import { findGuidance, globToRegex } from "../src/matcher"
import type { ChangeSet, Rule } from "../src/model"

const changes: ChangeSet = {
  addedFiles: [
    { path: "generated/client.ts" },
    { path: "schemas/X" },
    { path: "schemas/unapproved.json" },
    { path: "src/view.snap" },
  ],
  addedLines: [
    { path: "src/generated/client.ts", line: 3, content: "changed" },
    { path: "src/model.ts", line: 8, content: "export interface User {}" },
  ],
  deletedFiles: [{ path: "migrations/001.sql" }],
  deletedLines: [
    { path: "src/auth.ts", line: 12, content: "requirePermission(user)" },
  ],
}

describe("glob matching", () => {
  test("supports exact paths and recursive directories", () => {
    expect(globToRegex("src/generated/client.ts", false).test("src/generated/client.ts")).toBeTrue()
    expect(globToRegex("generated/**", false).test("generated/nested/client.ts")).toBeTrue()
    expect(globToRegex("**/*.ts", false).test("model.ts")).toBeTrue()
  })
})

describe("rule matching", () => {
  test("matches all four targets", () => {
    const rules: ReadonlyArray<Rule> = [
      {
        id: "generated-files",
        message: "Generated files are restricted.",
        target: "added-files",
        include: ["generated/**"],
      },
      {
        id: "immutable-client",
        message: "Do not edit this file.",
        target: "added-lines",
        include: ["src/generated/client.ts"],
      },
      {
        id: "migration-files",
        message: "Do not delete migrations.",
        target: "deleted-files",
        include: ["migrations/**"],
      },
      {
        id: "permission-lines",
        message: "Do not remove permission checks.",
        target: "deleted-lines",
        contentRegex: ["requirePermission"],
      },
    ]

    expect(findGuidance(rules, changes).map(({ id }) => id)).toEqual([
      "generated-files",
      "immutable-client",
      "migration-files",
      "permission-lines",
    ])
  })

  test("combines inclusive fields and removes exclusions", () => {
    const findings = findGuidance(
      [
        {
          id: "schema-names",
          message: "Only approved names are allowed.",
          target: "added-files",
          include: ["schemas/**"],
          excludeName: ["X", "Y", "Z"],
        },
        {
          id: "typescript-types",
          message: "Review new types.",
          target: "added-lines",
          extension: [".ts", ".tsx"],
          contentRegex: ["^\\s*(?:export\\s+)?(?:type|interface)\\s+"],
        },
      ],
      changes,
    )

    expect(findings[0]?.locations).toEqual([{ path: "schemas/unapproved.json" }])
    expect(findings[1]?.locations).toEqual([
      { path: "src/model.ts", line: 8, content: "export interface User {}" },
    ])
  })
})
